set_property PACKAGE_PIN V17 [get_ports {pins[0]}]
set_property PACKAGE_PIN V16 [get_ports {pins[1]}]
set_property PACKAGE_PIN W16 [get_ports {pins[2]}]
set_property PACKAGE_PIN W17 [get_ports {pins[3]}]
set_property PACKAGE_PIN W15 [get_ports {pins[4]}]
set_property PACKAGE_PIN V15 [get_ports {pins[5]}]
set_property PACKAGE_PIN W14 [get_ports {pins[6]}]
set_property PACKAGE_PIN W13 [get_ports {pins[7]}]
set_property PACKAGE_PIN V2 [get_ports {pins[8]}]
set_property PACKAGE_PIN T3 [get_ports {pins[9]}]
set_property PACKAGE_PIN T2 [get_ports {pins[10]}]
set_property PACKAGE_PIN R3 [get_ports {pins[11]}]
set_property PACKAGE_PIN W2 [get_ports {pins[12]}]
set_property PACKAGE_PIN U1 [get_ports {pins[13]}]
set_property PACKAGE_PIN T1 [get_ports {pins[14]}]
set_property PACKAGE_PIN R2 [get_ports {pins[15]}]
set_property PACKAGE_PIN U16 [get_ports {pins[16]}]
set_property PACKAGE_PIN E19 [get_ports {pins[17]}]
set_property PACKAGE_PIN U19 [get_ports {pins[18]}]
set_property PACKAGE_PIN V19 [get_ports {pins[19]}]
set_property PACKAGE_PIN W18 [get_ports {pins[20]}]
set_property PACKAGE_PIN U15 [get_ports {pins[21]}]
set_property PACKAGE_PIN U14 [get_ports {pins[22]}]
set_property PACKAGE_PIN V14 [get_ports {pins[23]}]
set_property PACKAGE_PIN V13 [get_ports {pins[24]}]
set_property PACKAGE_PIN V3 [get_ports {pins[25]}]
set_property PACKAGE_PIN W3 [get_ports {pins[26]}]
set_property PACKAGE_PIN U3 [get_ports {pins[27]}]
set_property PACKAGE_PIN P3 [get_ports {pins[28]}]
set_property PACKAGE_PIN N3 [get_ports {pins[29]}]
set_property PACKAGE_PIN P1 [get_ports {pins[30]}]
set_property PACKAGE_PIN L1 [get_ports {pins[31]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {pins[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pins[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]


create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

